create table if not exists person (
    id int primary key generated by default as identity ,
    name varchar(100) not null,
    age int check ( age < 100 ) not null
);


create table if not exists item  (
    id int primary key generated by default as identity ,
    person_id int references person(id) on delete set null ,
    item_name varchar(200) not null
);

insert into item (person_id, name)  values (1, 'HP notebook'),
                                                (1, 'Apple AirPods'),
                                                (2, 'Apple Iphone'),
                                                (3, 'Amazon Kindle'),
                                                (3, 'Apple TV'),
                                                (3, 'Sony PlayStation 5');